baseURL = "https://jjasghar.github.io/talks/"
languageCode = "en-us"
title = "Talks"
theme = "anatole"

[params]
title = "JJ's speaking engagements"
author = "JJ Asghar"
copyright = "2021-"
description = "List of past speaking engagements and featured talks."
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = []
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Linkedin"
url = "https://twitter.com/jjasghar"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/jjasghar"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jjasghar"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:jjasghar@gmail.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"